=== Jaumenc/Llenguatgemarques-/Simulacro_examen/index.dtd
<!ELEMENT escuela (baile+)>
<!ELEMENT baile (precio,plazas,fecha_inicio,fecha_finalizacion,dias_semana,nombre_profesor,sala)>
<!ATTLIST baile estilo CDATA #REQUIRED>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio periocidad CDATA #FIXED "1 mes"><!ATTLIST precio moneda NMTOKEN #FIXED "Euro">
<!ELEMENT plazas (#PCDATA)>
<!ELEMENT fecha_inicio (#PCDATA)>
<!ELEMENT fecha_finalizacion (#PCDATA)>
<!ELEMENT dias_semana (#PCDATA)>
<!ELEMENT nombre_profesor (#PCDATA)>
<!ELEMENT sala (#PCDATA)>

=== Jaumenc/Llenguatgemarques-/Simulacro_examen/index.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE escuela SYSTEM "index.dtd">
<escuela>
    <baile estilo="Salsa basico">
        <precio periocidad="1 mes" moneda="Euro">30 </precio>
        <plazas>20</plazas>
        <fecha_inicio>01/01</fecha_inicio>
        <fecha_finalizacion>30/06</fecha_finalizacion>
        <dias_semana>Lunes y Miercoles</dias_semana>
        <nombre_profesor>Bruno</nombre_profesor>
        <sala>1</sala>
    </baile>
    <baile estilo="Bachata basico">
        <precio periocidad="1 mes" moneda="Euro">30 </precio>
        <plazas>18</plazas>
        <fecha_inicio>01/02</fecha_inicio>
        <fecha_finalizacion>31/07</fecha_finalizacion>
        <dias_semana>Lunes y Miercoles</dias_semana>
        <nombre_profesor>Fiona</nombre_profesor>
        <sala>2</sala>
    </baile>
    <baile estilo="Merengue basico">
        <precio periocidad="1 mes" moneda="Euro">30 </precio>
        <plazas>16</plazas>
        <fecha_inicio>01/03</fecha_inicio>
        <fecha_finalizacion>31/08</fecha_finalizacion>
        <dias_semana>Lunes y Miercoles</dias_semana>
        <nombre_profesor>Sofia</nombre_profesor>
        <sala>3</sala>
    </baile>
    <baile estilo="Salsa avanzado">
        <precio periocidad="1 mes" moneda="Euro">60 </precio>
        <plazas>20</plazas>
        <fecha_inicio>01/07</fecha_inicio>
        <fecha_finalizacion>31/12</fecha_finalizacion>
        <dias_semana>Martes y Jueves</dias_semana>
        <nombre_profesor>Sofia</nombre_profesor>
        <sala>2</sala>
    </baile>
    <baile estilo="Bachata avanzado">
        <precio periocidad="1 mes" moneda="Euro">60 </precio>
        <plazas>18</plazas>
        <fecha_inicio>01/08</fecha_inicio>
        <fecha_finalizacion>30/01</fecha_finalizacion>
        <dias_semana>Martes y Jueves</dias_semana>
        <nombre_profesor>Bruno</nombre_profesor>
        <sala>3</sala>
    </baile>
    <baile estilo="Merengue avanzado">
        <precio periocidad="1 mes" moneda="Euro">60 </precio>
        <plazas>16</plazas>
        <fecha_inicio>01/09</fecha_inicio>
        <fecha_finalizacion>28/02</fecha_finalizacion>
        <dias_semana>Martes y Jueves</dias_semana>
        <nombre_profesor>Fiona</nombre_profesor>
        <sala>1</sala>
    </baile>
</escuela>
